### ISSUE TITLE
UntarFiles extracts pax_global_header

### ISSUE THREAD

**Issue by cassava** [juju/utils#160]
When using UntarFiles on a tar created by git, it will extract pax_global_header as a file.
I'm not sure if this is a problem with the standard library or here.
See https://gcc.gnu.org/ml/gcc/2006-03/msg00052.html for more on that.

**Comment by axw** [comment]
@cassava Sorry for taking so long to respond. If you still care, #181 should resolve this.

**Comment by cassava** [comment]
@axw Thanks!
